version: '3.8'

networks:
  oriiyx-network:
    driver: bridge

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
      - "443:443"
    networks:
      - oriiyx-network


